name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: install
        run: make install

      - name: run linter
        run: make lint
    
      - name: run jest
        run: make test-c
